export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

// This type will be auto-generated by Supabase CLI later.
// For now, define a minimal skeleton so the client is typed.
export interface Database {
  public: {
    Tables: {
      rutas: {
        Row: {
          id_ruta: number;
          nombre: string;
          codigo: string;
          origen: string;
          destino: string;
          activo: boolean;
          creado_en: string;
        };
        Insert: {
          id_ruta?: number;
          nombre: string;
          codigo: string;
          origen: string;
          destino: string;
          activo?: boolean;
          creado_en?: string;
        };
        Update: {
          id_ruta?: number;
          nombre?: string;
          codigo?: string;
          origen?: string;
          destino?: string;
          activo?: boolean;
          creado_en?: string;
        };
        Relationships: [];
      };
      reservaciones: {
        Row: {
          id_reservacion: number;
          usuario_id: string;
          ruta_id: number;
          viaje_id: number | null;
          fecha_reserva: string;
          asientos: number;
          estado: string;
          total: number;
        };
        Insert: {
          id_reservacion?: number;
          usuario_id: string;
          ruta_id: number;
          viaje_id?: number | null;
          fecha_reserva?: string;
          asientos?: number;
          estado?: string;
          total: number;
        };
        Update: {
          id_reservacion?: number;
          usuario_id?: string;
          ruta_id?: number;
          viaje_id?: number | null;
          fecha_reserva?: string;
          asientos?: number;
          estado?: string;
          total?: number;
        };
        Relationships: [
          {
            foreignKeyName: "reservaciones_ruta_id_fkey";
            columns: ["ruta_id"];
            isOneToOne: false;
            referencedRelation: "rutas";
            referencedColumns: ["id_ruta"];
          },
        ];
      };
      tickets: {
        Row: {
          id_ticket: number;
          reservacion_id: number;
          codigo_ticket: string;
          asiento: string | null;
          estado: string;
          emitido_en: string;
        };
        Insert: {
          id_ticket?: number;
          reservacion_id: number;
          codigo_ticket: string;
          asiento?: string | null;
          estado?: string;
          emitido_en?: string;
        };
        Update: {
          id_ticket?: number;
          reservacion_id?: number;
          codigo_ticket?: string;
          asiento?: string | null;
          estado?: string;
          emitido_en?: string;
        };
        Relationships: [
          {
            foreignKeyName: "tickets_reservacion_id_fkey";
            columns: ["reservacion_id"];
            isOneToOne: false;
            referencedRelation: "reservaciones";
            referencedColumns: ["id_reservacion"];
          },
        ];
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
  };
}
