export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

// This type will be auto-generated by Supabase CLI later.
// For now, define a minimal skeleton so the client is typed.
export interface Database {
  public: {
    Tables: {
      rutas: {
        Row: {
          id_ruta: number;
          nombre: string;
          codigo: string;
          origen: string;
          destino: string;
          activo: boolean;
          creado_en: string;
        };
        Insert: {
          id_ruta?: number;
          nombre: string;
          codigo: string;
          origen: string;
          destino: string;
          activo?: boolean;
          creado_en?: string;
        };
        Update: {
          id_ruta?: number;
          nombre?: string;
          codigo?: string;
          origen?: string;
          destino?: string;
          activo?: boolean;
          creado_en?: string;
        };
      };
      tickets: {
        Row: {
          id: string;
          user_id: string;
          route_id: string;
          qr_code: string;
          status: "active" | "used" | "expired" | "cancelled";
          purchased_at: string;
          expires_at: string;
          validated_at: string | null;
          validated_by: string | null;
        };
        Insert: {
          id?: string;
          user_id: string;
          route_id: string;
          qr_code?: string;
          status?: "active" | "used" | "expired" | "cancelled";
          purchased_at?: string;
          expires_at: string;
          validated_at?: string | null;
          validated_by?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string;
          route_id?: string;
          qr_code?: string;
          status?: "active" | "used" | "expired" | "cancelled";
          purchased_at?: string;
          expires_at?: string;
          validated_at?: string | null;
          validated_by?: string | null;
        };
      };
      // TODO: Add remaining tables once schema is shared
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
  };
}
